"""GDP Report Templates — MCP Prompts for standardized, professional output.

Each prompt is a report template that instructs the AI to:
  1. Call specific GDP tools in a defined order
  2. Gather all relevant data
  3. Format results in a consistent, professional structure

This ensures that the same report generates the same format every time,
regardless of who runs it — Devan's #1 request for demo consistency.
"""

from __future__ import annotations

import logging

logger = logging.getLogger("gdp_mcp")


def register_prompts(mcp) -> None:
    """Register all GDP report template prompts on the given FastMCP instance."""

    # ── 1. Security Assessment Report ───────────────────────────

    @mcp.prompt(
        name="security_assessment_report",
        description=(
            "Generate a comprehensive Security Assessment Report for a GDP appliance. "
            "Covers datasources, policies, violations, system health, and recommendations."
        ),
    )
    def security_assessment_report(
        appliance: str = "",
        time_period: str = "last 30 days",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate a **Security Assessment Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data for each section.

---

# 🔒 GDP Security Assessment Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname and IP from system info]
**Period:** {time_period}
**Generated by:** GDP MCP Server

---

## Executive Summary

Write a 2-3 sentence summary of the overall security posture based on the data gathered below.

---

## 1. Monitored Datasources

**Action:** Call `gdp_search_apis("datasource")` → then `gdp_execute_api("list_datasource")`{appl_clause}

Present results as a table:

| # | Datasource Name | Type | Host | Port | Status |
|---|----------------|------|------|------|--------|

State the total count and highlight any datasources with connectivity issues.

---

## 2. Security Policies

**Action:** Call `gdp_search_apis("policy")` → find the list policies API → `gdp_execute_api` to list all policies{appl_clause}

Present results as a table:

| # | Policy Name | Type | Status | Last Modified |
|---|------------|------|--------|---------------|

State the total count. Note any disabled or misconfigured policies.

---

## 3. Violations Summary

**Action:** Call `gdp_search_apis("violation")` → find violation listing APIs → execute them{appl_clause}

Present:
- Total violation count for the period
- Breakdown by severity (Critical / High / Medium / Low)
- Top 5 violation types by frequency

| Severity | Count | % of Total |
|----------|-------|-----------|

---

## 4. System Health

**Action:** Call `gdp_guard_cli("show system info")`{appl_clause}, then `gdp_guard_cli("diag system memory")`{appl_clause}, then `gdp_guard_cli("diag system disk")`{appl_clause}

Present:
- **GDP Version:** [from system info]
- **Uptime:** [from system info]
- **CPU:** [utilization]
- **Memory:** [used / total, percentage]
- **Disk:** [used / total, percentage]

Flag any resource utilization above 80% as ⚠️ Warning.

---

## 5. Recommendations

Based on the data gathered above, provide 3-5 actionable recommendations. Prioritize by impact:

1. **[Critical]** ...
2. **[High]** ...
3. **[Medium]** ...

---

## Report Footer

> This report was generated automatically by the GDP MCP Server using live data from the GDP appliance. All data reflects the state at the time of generation.

---

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate or assume any values. If a tool call fails or data is unavailable, state "Data unavailable — [reason]" in that section."""

    # ── 2. Compliance Summary Report ────────────────────────────

    @mcp.prompt(
        name="compliance_summary_report",
        description=(
            "Generate a Compliance Summary Report showing policy status, "
            "violation trends, and compliance posture across the GDP environment."
        ),
    )
    def compliance_summary_report(
        appliance: str = "",
        framework: str = "general",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate a **Compliance Summary Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data for each section.

---

# 📋 GDP Compliance Summary Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname and IP]
**Framework:** {framework}
**Generated by:** GDP MCP Server

---

## Compliance Score

Calculate a compliance score based on: policies enabled vs total, violation rate, monitoring coverage.

Present as: **[X]%** — [Good / Needs Attention / Critical]

---

## 1. Policy Coverage

**Action:** Call `gdp_search_apis("policy")` → list all policies → execute{appl_clause}

| # | Policy Name | Type | Enabled | Compliant |
|---|------------|------|---------|-----------|

- **Total Policies:** [count]
- **Enabled:** [count] ([%])
- **Disabled:** [count] — list them

---

## 2. Monitoring Coverage

**Action:** Call `gdp_execute_api("list_datasource")`{appl_clause}

- **Total Datasources:** [count]
- **Actively Monitored:** [count]
- **Not Monitored:** [count] — list them

Coverage ratio: **[X]%**

---

## 3. Violations by Category

**Action:** Call `gdp_search_apis("violation")` → execute violation listing APIs{appl_clause}

| Category | Count | Trend (↑/↓/→) |
|----------|-------|----------------|

---

## 4. Compliance Gaps

List specific gaps found:

1. **[Gap]** — [Description] — **Impact:** [High/Medium/Low]
2. ...

---

## 5. Remediation Recommendations

For each gap identified above, provide a specific remediation step:

| # | Gap | Remediation | Priority |
|---|-----|-------------|----------|

---

> This report was generated automatically by the GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    # ── 3. Datasource Inventory Report ──────────────────────────

    @mcp.prompt(
        name="datasource_inventory_report",
        description=(
            "Generate a Datasource Inventory Report listing all monitored "
            "datasources with connection details, types, and status."
        ),
    )
    def datasource_inventory_report(
        appliance: str = "",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate a **Datasource Inventory Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data.

---

# 🗄️ GDP Datasource Inventory Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname]
**Generated by:** GDP MCP Server

---

## Summary

- **Total Datasources:** [count]
- **Database Types:** [list unique types with counts]
- **Active Connections:** [count]

---

## Datasource Details

**Action:** Call `gdp_search_apis("datasource")` → then `gdp_execute_api("list_datasource")`{appl_clause}

Present ALL datasources as a detailed table:

| # | Name | Database Type | Host | Port | Status | S-TAP | Last Activity |
|---|------|--------------|------|------|--------|-------|---------------|

---

## Datasources by Type

Group datasources by database type:

### [Database Type 1]
- [datasource 1]
- [datasource 2]

### [Database Type 2]
- ...

---

## Connectivity Issues

List any datasources with problems:

| Datasource | Issue | Recommended Action |
|-----------|-------|--------------------|

If all datasources are healthy, state: "✅ All datasources reporting normally."

---

> Generated automatically by GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    # ── 4. Activity Monitoring Report ───────────────────────────

    @mcp.prompt(
        name="activity_monitoring_report",
        description=(
            "Generate an Activity Monitoring Report showing database activity "
            "patterns, top users, and anomalies detected by GDP."
        ),
    )
    def activity_monitoring_report(
        appliance: str = "",
        time_period: str = "last 7 days",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate an **Activity Monitoring Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data.

---

# 📊 GDP Activity Monitoring Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname]
**Period:** {time_period}
**Generated by:** GDP MCP Server

---

## Summary

High-level activity metrics for the period.

---

## 1. Activity Volume

**Action:** Call `gdp_search_apis("report")` → find activity-related reports → execute them{appl_clause}

- **Total Events:** [count]
- **Unique Users:** [count]
- **Unique Datasources:** [count]

---

## 2. Top Database Users

| # | User | Events | Datasources Accessed | Last Active |
|---|------|--------|---------------------|-------------|

---

## 3. Activity by Datasource

| # | Datasource | Events | Unique Users | Peak Hours |
|---|-----------|--------|-------------|------------|

---

## 4. Anomalies & Alerts

List any unusual patterns or triggered alerts:

| Alert | Description | Severity | Time |
|-------|-------------|----------|------|

If no anomalies: "✅ No anomalies detected in the reporting period."

---

## 5. Recommendations

Based on the activity data, provide recommendations for security tuning.

---

> Generated automatically by GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    # ── 5. System Health Report ─────────────────────────────────

    @mcp.prompt(
        name="system_health_report",
        description=(
            "Generate a System Health Report using Guard CLI diagnostics — "
            "CPU, memory, disk, processes, and network status."
        ),
    )
    def system_health_report(
        appliance: str = "",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate a **System Health Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use GDP MCP tools (especially Guard CLI) to gather real data.

---

# 🏥 GDP System Health Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname and IP]
**Generated by:** GDP MCP Server

---

## System Overview

**Action:** Call `gdp_guard_cli("show system info")`{appl_clause}

- **GDP Version:** [version]
- **Hostname:** [hostname]
- **Uptime:** [uptime]
- **Last Patch:** [if available]

---

## Resource Utilization

### Memory
**Action:** Call `gdp_guard_cli("diag system memory")`{appl_clause}

| Metric | Value | Status |
|--------|-------|--------|
| Total Memory | [X] GB | — |
| Used Memory | [X] GB | [✅ OK / ⚠️ High / 🔴 Critical] |
| Free Memory | [X] GB | — |
| Utilization | [X]% | [status based on thresholds: <70% OK, 70-85% High, >85% Critical] |

### Disk
**Action:** Call `gdp_guard_cli("diag system disk")`{appl_clause}

| Filesystem | Size | Used | Available | Use% | Status |
|-----------|------|------|-----------|------|--------|

Flag any partition above 80% usage.

---

## Network Configuration

**Action:** Call `gdp_guard_cli("show network interface all")`{appl_clause}

| Interface | IP Address | Status |
|-----------|-----------|--------|

---

## Running Processes

**Action:** Call `gdp_guard_cli("show system processes")`{appl_clause}

List key GDP processes and their status:

| Process | Status | PID |
|---------|--------|-----|

---

## Inspection Engines (S-TAPs)

**Action:** Call `gdp_search_apis("stap")` → find S-TAP listing API → execute{appl_clause}

| # | S-TAP Name | Host | Status | Version |
|---|-----------|------|--------|---------|

---

## Health Summary

| Component | Status | Notes |
|-----------|--------|-------|
| GDP Application | [✅/⚠️/🔴] | ... |
| Memory | [✅/⚠️/🔴] | ... |
| Disk | [✅/⚠️/🔴] | ... |
| Network | [✅/⚠️/🔴] | ... |
| S-TAPs | [✅/⚠️/🔴] | ... |

**Overall Health:** [✅ Healthy / ⚠️ Needs Attention / 🔴 Critical]

---

## Recommendations

1. ...
2. ...
3. ...

---

> Generated automatically by GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    # ── 6. Vulnerability Assessment Report ──────────────────────

    @mcp.prompt(
        name="vulnerability_assessment_report",
        description=(
            "Generate a Vulnerability Assessment Report covering VA scan "
            "results, findings by severity, and remediation guidance."
        ),
    )
    def vulnerability_assessment_report(
        appliance: str = "",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate a **Vulnerability Assessment Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data.

---

# 🛡️ GDP Vulnerability Assessment Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname]
**Generated by:** GDP MCP Server

---

## Summary

- **Total Findings:** [count]
- **Critical:** [count] 🔴
- **High:** [count] 🟠
- **Medium:** [count] 🟡
- **Low:** [count] 🟢

---

## 1. VA Scan Results

**Action:** Call `gdp_search_apis("vulnerability")` → find VA-related APIs → execute them{appl_clause}

Also try: `gdp_search_apis("assessment")`, `gdp_search_apis("scan")`

Present results grouped by severity:

### 🔴 Critical Findings

| # | Finding | Datasource | Description | Remediation |
|---|---------|-----------|-------------|-------------|

### 🟠 High Findings

| # | Finding | Datasource | Description | Remediation |
|---|---------|-----------|-------------|-------------|

### 🟡 Medium Findings

| # | Finding | Datasource | Description | Remediation |
|---|---------|-----------|-------------|-------------|

---

## 2. Findings by Datasource

| Datasource | Critical | High | Medium | Low | Total |
|-----------|----------|------|--------|-----|-------|

---

## 3. Remediation Priority

Ordered list of actions by impact:

| # | Action | Affected Datasources | Severity | Effort |
|---|--------|---------------------|----------|--------|

---

## 4. VA Test Coverage

- **Datasources with VA enabled:** [count] of [total]
- **VA coverage:** [X]%
- **Datasources missing VA:** [list them]

---

> Generated automatically by GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    # ── 7. S-TAP Status Report ──────────────────────────────────

    @mcp.prompt(
        name="stap_status_report",
        description=(
            "Generate an S-TAP Status Report showing all inspection engines, "
            "their connectivity, versions, and monitored datasources."
        ),
    )
    def stap_status_report(
        appliance: str = "",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate an **S-TAP Status Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data.

---

# 📡 GDP S-TAP Status Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname]
**Generated by:** GDP MCP Server

---

## Summary

- **Total S-TAPs:** [count]
- **Active:** [count] ✅
- **Inactive/Down:** [count] 🔴
- **Availability:** [X]%

---

## S-TAP Inventory

**Action:** Call `gdp_search_apis("stap")` → find S-TAP listing APIs → execute them{appl_clause}

Also try: `gdp_search_apis("inspection")`, `gdp_search_apis("agent")`

| # | S-TAP Name | Host | IP | Version | Status | Last Heartbeat |
|---|-----------|------|-----|---------|--------|----------------|

---

## S-TAP Details

For each S-TAP, provide:

### [S-TAP Name]
- **Host:** [hostname/IP]
- **Status:** [Active/Inactive]
- **Version:** [version]
- **Monitored Datasources:** [list]
- **Inspection Engines:** [running/configured counts]

---

## Connectivity Issues

| S-TAP | Issue | Duration | Recommended Action |
|-------|-------|----------|-------------------|

If all S-TAPs are healthy: "✅ All S-TAPs reporting normally."

---

## Version Compliance

| Version | Count | Up to Date? |
|---------|-------|-------------|

Flag any S-TAPs running outdated versions.

---

> Generated automatically by GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    # ── 8. Policy Violations Report ─────────────────────────────

    @mcp.prompt(
        name="policy_violations_report",
        description=(
            "Generate a Policy Violations Report with violation details, "
            "trends, affected users, and remediation steps."
        ),
    )
    def policy_violations_report(
        appliance: str = "",
        time_period: str = "last 30 days",
    ) -> str:
        appl_clause = f' on appliance "{appliance}"' if appliance else ""
        return f"""Generate a **Policy Violations Report** for the GDP appliance{appl_clause}.

Follow this exact structure. Use the GDP MCP tools to gather real data.

---

# ⚠️ GDP Policy Violations Report

**Generated:** [current date and time]
**Appliance:** [appliance hostname]
**Period:** {time_period}
**Generated by:** GDP MCP Server

---

## Summary

- **Total Violations:** [count]
- **Unique Policies Violated:** [count]
- **Unique Users Involved:** [count]
- **Most Violated Policy:** [name] ([count] violations)

---

## 1. Violations by Policy

**Action:** Call `gdp_search_apis("violation")` → find violation listing APIs → execute them{appl_clause}

| # | Policy | Violations | Severity | % of Total |
|---|--------|-----------|----------|-----------|

---

## 2. Violations by Severity

| Severity | Count | Percentage |
|----------|-------|-----------|
| Critical | [count] | [%] |
| High | [count] | [%] |
| Medium | [count] | [%] |
| Low | [count] | [%] |

---

## 3. Top Violating Users

| # | User | Violations | Policies Violated | Datasources |
|---|------|-----------|-------------------|-------------|

---

## 4. Violations by Datasource

| # | Datasource | Violations | Top Policy | Severity |
|---|-----------|-----------|-----------|----------|

---

## 5. Recent Violations (Last 10)

| Time | User | Policy | Datasource | Action | Severity |
|------|------|--------|-----------|--------|----------|

---

## 6. Remediation Actions

| # | Issue | Affected Scope | Recommended Action | Priority |
|---|-------|---------------|-------------------|----------|

---

> Generated automatically by GDP MCP Server using live data.

**IMPORTANT:** Use ONLY real data from the GDP tools. Do not fabricate any values."""

    logger.info("Registered 8 report template prompts")
